<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FrameAgricultureApi.Enumerators\FrameAgricultureApi.Enumerators.csproj" />
    <ProjectReference Include="..\FrameAgricultureApi.Generic\FrameAgricultureApi.Generic.csproj" />
    <ProjectReference Include="..\FrameAgricultureApi.Libraries.LookUps\FrameAgricultureApi.Libraries.LookUps.csproj" />
    <ProjectReference Include="..\FrameAgricultureApi.Libraries.ManureManagement\FrameAgricultureApi.Libraries.ManureManagement.csproj" />
    <ProjectReference Include="..\FrameAgricultureApi.Libraries.GrassResidues\FrameAgricultureApi.Libraries.GrassResidues.csproj" />
  </ItemGroup>

</Project>
